name: Test with ESLint

on: [push, pull_request]

jobs:
  test-Linter:
    runs-on: ubuntu-latest
    name: Test with ESLint

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run eslint
